"""rename address

Revision ID: 2faab00e9e23
Revises: e2a9d286d4a2
Create Date: 2024-08-06 23:14:19.488607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2faab00e9e23'
down_revision = 'e2a9d286d4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')  
    # ### end Alembic commands ###
