"""rename department

Revision ID: e2a9d286d4a2
Revises: 4431c58afc2f
Create Date: 2024-08-06 23:09:36.761250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a9d286d4a2'
down_revision = '4431c58afc2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('deparment', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'deparment')
    # ### end Alembic commands ###
